### ISSUE TITLE
check Python version compatibility

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/tool-migration#13]
When @ziegler1960 ran the application he got a different response than when I ran it.  I was using Python 3.11.  The response I got was…

```
INFO:__main__:Warehouse connection is configured, so it will be used for some data fetching...
INFO:__main__:Number of tools found in account 109: 57
Traceback (most recent call last):
  File "/Users/lsloan/Projects/tool-migration/tl_tool-migration/migration/main.py", line 148, in <module>
    trio.run(
  File "/Users/lsloan/Projects/tool-migration/tl_tool-migration/.venv/lib/python3.11/site-packages/trio/_core/_run.py", line 2085, in run
    raise runner.main_task_outcome.error
  File "/Users/lsloan/Projects/tool-migration/tl_tool-migration/migration/utils.py", line 57, in wrapper
    result = await callable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/tool-migration/tl_tool-migration/migration/main.py", line 73, in main
    tool_pairs = find_tools_for_migrations(tools, migrations)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/tool-migration/tl_tool-migration/migration/main.py", line 42, in find_tools_for_migrations
    raise InvalidToolIdsException(
exceptions.InvalidToolIdsException: The following tool IDs from one of your migrations were not found in the account: [49610]
```

Which indicates we may have chosen the wrong tool ID.  No problem, that's a simple mistake and is probably simple to fix by picking a better one.

When @ziegler1960 tested the application, he got the response…

```
Traceback (most recent call last):
File "migration/main.py", line 9, in <module>
from api import API
File "/Users/ziegler/tool-migration-main/migration/api.py", line 29, in <module> 
class GetResponse:
File "/Users/ziegler/tool-migration-main/migration/api.py", line 31, in GetResponse 
next_page_params: dict[str, Any] | None
TypeError: 'type' object is not subscriptable
```

That kind of error message seems to indicate a problem with the `dict[str, Any]` typing.  That error could come from running the program with an older version of Python that does not support that kind of typing.

@ziegler1960 says he thinks the version of Python on his computer is version 3.11, but I think he and I will need to check that to be sure.

If the problem is caused by using an older version of Python, then the documentation should specify which version is required and the application should check that it is running with the required version.

**Comment by lsloan** [comment]
This had been an issue in the earliest days of testing with @ziegler1960.  After that, in #15 we switched to using Docker compose to manage the application environment, which was better, but still depended on his poor network connection.  Moving to running in OpenShift in #25 has resolved this issue and removes his network from the dependencies.
